name: apptesoritoslau
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 4.11.0
  firebase_storage: 11.3.1
  provider: 6.0.5
  flutter_bloc: 8.1.0
  equatable: 2.0.5
  easy_debounce: 2.0.3
  google_fonts: 6.1.0
  animations: 2.0.8
  badges: 2.0.2
  auto_size_text: 3.0.0
  firebase_core: 2.19.0
  firebase_auth: 4.11.1
  firebase_ui_auth: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
