// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_eHf_5zQH8Nal4G-_eCMlL2jL8pepwc',
    appId: '1:24386170273:web:d06256d945e28024cbefe0',
    messagingSenderId: '24386170273',
    projectId: 'app-tesoritos-lau',
    authDomain: 'app-tesoritos-lau.firebaseapp.com',
    storageBucket: 'app-tesoritos-lau.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnLYao60DJPlreVSsSo7C8qlSOqAWbNmc',
    appId: '1:24386170273:android:5ba4fd8fc1b9c96ecbefe0',
    messagingSenderId: '24386170273',
    projectId: 'app-tesoritos-lau',
    storageBucket: 'app-tesoritos-lau.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ttaZZOex_brBua6PQtbXsQky3GiM860',
    appId: '1:24386170273:ios:33a297b78fb68470cbefe0',
    messagingSenderId: '24386170273',
    projectId: 'app-tesoritos-lau',
    storageBucket: 'app-tesoritos-lau.appspot.com',
    iosBundleId: 'com.example.apptesoritoslau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ttaZZOex_brBua6PQtbXsQky3GiM860',
    appId: '1:24386170273:ios:f466859e26891939cbefe0',
    messagingSenderId: '24386170273',
    projectId: 'app-tesoritos-lau',
    storageBucket: 'app-tesoritos-lau.appspot.com',
    iosBundleId: 'com.example.apptesoritoslau.RunnerTests',
  );
}
